artifact_location: file:///home/mle-user/mle-projects/mle-mlflow/mlflow_experiments_store/0
creation_time: 1754228504687
experiment_id: '0'
last_update_time: 1754228504687
lifecycle_stage: active
name: Default
